acts_camdram_diary_date:
    path:  /{start}.{_format}
    defaults:
        _controller: Acts\CamdramBundle\Controller\DiaryController::dateAction
        _format: html
    requirements:
        start: '[0-9]{4}\-[0-9]{2}\-[0-9]{2}'

acts_camdram_diary_year:
    path:  /{year}.{_format}
    defaults:
        _controller: Acts\CamdramBundle\Controller\DiaryController::yearAction
        _format: html
    requirements:
        year: "[0-9]{4}"

acts_camdram_diary_period:
    path:  /{year}/{period}.{_format}
    defaults:
        _controller: Acts\CamdramBundle\Controller\DiaryController::periodAction
        _format: html
    requirements:
        year: "[0-9]{4}"

acts_camdram_diary_week:
    path:  /{year}/{period}/{week}.{_format}
    defaults:
        _controller: Acts\CamdramBundle\Controller\DiaryController::weekAction
        _format: html
    requirements:
        year: "[0-9]{4}"

acts_camdram_diary_single_week:
    path:  /week/{date}.{_format}
    defaults:
        _controller: Acts\CamdramBundle\Controller\DiaryController::singleWeekAction
        _format: html
