version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: jms/serializer-bundle
    versions:
    - "< 3.0.2, >= 3.0.1.a"
  - dependency-name: jms/serializer-bundle
    versions:
    - ">= 3.1.0.a, < 3.1.1"
  - dependency-name: zurb/foundation
    versions:
    - "> 4.3.2"
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.85
  - dependency-name: doctrine/orm
    versions:
    - 2.8.2
    - 2.8.3
    - 2.8.4
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: doctrine/doctrine-bundle
    versions:
    - 2.2.4
    - 2.3.0
    - 2.3.1
  - dependency-name: symfony/security-bundle
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/translation
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/monolog-bundle
    versions:
    - 3.7.0
  - dependency-name: symfony/form
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/validator
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: jms/serializer-bundle
    versions:
    - 3.9.0
    - 3.9.1
  - dependency-name: sentry/sentry-symfony
    versions:
    - 4.0.3
    - 4.1.0
  - dependency-name: laminas/laminas-feed
    versions:
    - 2.14.0
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/mime
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/console
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: stof/doctrine-extensions-bundle
    versions:
    - 1.6.0
  - dependency-name: sensio/framework-extra-bundle
    versions:
    - 6.0.0
    - 6.1.0
    - 6.1.1
  - dependency-name: symfony/expression-language
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/asset
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/web-profiler-bundle
    versions:
    - 5.2.4
  - dependency-name: symfony/intl
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: php-http/guzzle6-adapter
    versions:
    - 2.0.2
  - dependency-name: symfony/twig-bundle
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/web-server-bundle
    versions:
    - 4.4.20
  - dependency-name: symfony/debug-bundle
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/webpack-encore-bundle
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.1
  - dependency-name: symfony/polyfill-intl-messageformatter
    versions:
    - 1.22.1
  - dependency-name: php-http/httplug-bundle
    versions:
    - 1.20.1
  - dependency-name: sabre/vobject
    versions:
    - 4.3.5
  - dependency-name: oneup/uploader-bundle
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: phpstan/phpstan-symfony
    versions:
    - 0.12.17
    - 0.12.18
  - dependency-name: hwi/oauth-bundle
    versions:
    - 1.3.0
  - dependency-name: twig/twig
    versions:
    - 3.3.0
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.3
  - dependency-name: symfony/css-selector
    versions:
    - 5.2.3
  registries:
  - git-github-com
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@github/hotkey"
    versions:
    - 1.4.3
    - 1.4.4
  - dependency-name: dropzone
    versions:
    - 5.7.3
    - 5.7.5
    - 5.7.6
    - 5.8.0
    - 5.8.1
    - 5.9.0
    - 5.9.1
  - dependency-name: "@symfony/webpack-encore"
    versions:
    - 1.0.1
    - 1.0.2
    - 1.0.4
    - 1.0.6
    - 1.1.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: webpack-notifier
    versions:
    - 1.13.0
  registries:
  - git-github-com
