version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "05:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
