#!/bin/bash
set -e
# Perform initial installaion with Elasticsearch stopped
sudo service elasticsearch stop
# Install deps again, which will create a new parameters.yml with default values
composer create-project camdram/camdram $HOME/camdramdev dev-master#$TRAVIS_COMMIT --no-interaction --keep-vcs
cd $HOME/camdramdev
# Start Elasticsearch and populate index
sudo service elasticsearch start
sleep 10
php app/console fos:elastica:populate
