#!/bin/sh
SCRIPT=$(readlink -f "$0")
CWD=$(dirname "$SCRIPT")

# install sphinxsearch:
sudo add-apt-repository ppa:builds/sphinxsearch-rel21 -y
sudo apt-get update
sudo apt-get install sphinxsearch

# run searchd:
php app/console --env=test_sphinx acts:sphinx:config
sudo ln -sf $CWD/app/config/sphinx.default.cfg ./sphinx.conf
sudo searchd