#!/bin/bash
set -e
export SYMFONY_DEPRECATIONS_HELPER=weak_vendors
export SYMFONY_ENV=test

PHPUNIT_ARGS=""
BEHAT_ARGS=""

for i in "$@"
do
case $i in
    -s|--exclude-search)
    PHPUNIT_ARGS="--exclude-group search"
    BEHAT_ARGS="--tags ~@search"
    shift # past argument=value
    ;;
    *)
        echo "Unkown argument: $i"
        exit 1
    ;;
esac
done


php app/console lint:yaml app/config
php app/console lint:twig app/Resources
php app/console doctrine:schema:update --force
bin/simple-phpunit $PHPUNIT_ARGS
bin/behat $BEHAT_ARGS
php app/console security:check --end-point=http://security.sensiolabs.org/check_lock