parameters:
#    acts_camdram_legacy.example.class: Acts\CamdramLegacyBundle\Example

services:
#    acts_camdram_legacy.example:
#        class: %acts_camdram_legacy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    acts.camdram.listener.show_ref:
        class: Acts\CamdramLegacyBundle\EventListener\ShowRefCreator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: camdram.entity_created, method: onShowCreated }

    acts.camdram.redirect_handler:
        class: Acts\CamdramLegacyBundle\EventListener\RedirectHandler
        arguments:  [@router, @doctrine.orm.entity_manager, %v1_hostname%]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }