acts_camdram_api_homepage:
    path:  /
    defaults: { _controller: ActsCamdramApiBundle:Default:index }

acts_camdram_api_test_console:
    path:  /test-console
    defaults: { _controller: ActsCamdramApiBundle:Default:testConsole }

acts_camdram_api_apps:
    type: rest
    resource: "Acts\CamdramApiBundle\Controller\AppController"
