imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            excluded_404s: [^/]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!camdram", "!mailer"]
        actions:
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%.action.log"
            channels: ["camdram"]
        mailer:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.mailer.log"
            channels: ["mailer"]

sentry:
    dsn: "%env(SENTRY_DSN)%"
