<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121226112627 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE acts_news_links (id INT AUTO_INCREMENT NOT NULL, news_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, link VARCHAR(255) NOT NULL, source VARCHAR(255) NULL, media_type VARCHAR(20) NULL, description LONGTEXT NULL, picture VARCHAR(255) NULL, INDEX IDX_56C215DAB5A459A0 (news_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE acts_news_mentions (id INT AUTO_INCREMENT NOT NULL, news_id INT DEFAULT NULL, entity_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, remote_id VARCHAR(255) NOT NULL, service VARCHAR(20) NOT NULL, offset INT NOT NULL, length INT NOT NULL, INDEX IDX_9A671BDAB5A459A0 (news_id), INDEX IDX_9A671BDA81257D5D (entity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE acts_news_links ADD CONSTRAINT FK_56C215DAB5A459A0 FOREIGN KEY (news_id) REFERENCES acts_news (id)");
        $this->addSql("ALTER TABLE acts_news_mentions ADD CONSTRAINT FK_9A671BDAB5A459A0 FOREIGN KEY (news_id) REFERENCES acts_news (id)");
        $this->addSql("ALTER TABLE acts_news_mentions ADD CONSTRAINT FK_9A671BDA81257D5D FOREIGN KEY (entity_id) REFERENCES acts_societies (id)");
        $this->addSql("ALTER TABLE acts_news ADD picture VARCHAR(255) DEFAULT NULL, ADD posted_at DATETIME NOT NULL, ADD created_at DATETIME NOT NULL");
        $this->addSql("ALTER TABLE acts_societies ADD address LONGTEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE acts_societies DROP address");
        $this->addSql("DROP TABLE acts_news_links");
        $this->addSql("DROP TABLE acts_news_mentions");
        $this->addSql("ALTER TABLE acts_news DROP picture, DROP posted_at, DROP created_at");
    }
}
