<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121204231735 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE acts_shows_refs CHANGE showid showid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_shows_refs ADD CONSTRAINT FK_86C0B071592D0E6F FOREIGN KEY (showid) REFERENCES acts_shows (id)");
        $this->addSql("CREATE INDEX IDX_86C0B071592D0E6F ON acts_shows_refs (showid)");
        $this->addSql("ALTER TABLE acts_applications CHANGE showid showid INT DEFAULT NULL, CHANGE socid socid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_applications ADD CONSTRAINT FK_95ED3F0F592D0E6F FOREIGN KEY (showid) REFERENCES acts_shows (id)");
        $this->addSql("ALTER TABLE acts_applications ADD CONSTRAINT FK_95ED3F0FAF648A81 FOREIGN KEY (socid) REFERENCES acts_societies (id)");
        $this->addSql("CREATE INDEX IDX_95ED3F0F592D0E6F ON acts_applications (showid)");
        $this->addSql("CREATE INDEX IDX_95ED3F0FAF648A81 ON acts_applications (socid)");
        $this->addSql("ALTER TABLE acts_auditions CHANGE showid showid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_auditions ADD CONSTRAINT FK_BFECDAF7592D0E6F FOREIGN KEY (showid) REFERENCES acts_shows (id)");
        $this->addSql("CREATE INDEX IDX_BFECDAF7592D0E6F ON acts_auditions (showid)");
        $this->addSql("ALTER TABLE acts_shows_people_link CHANGE sid sid INT DEFAULT NULL, CHANGE pid pid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_shows_people_link ADD CONSTRAINT FK_2F5AB85E57167AB4 FOREIGN KEY (sid) REFERENCES acts_shows (id)");
        $this->addSql("ALTER TABLE acts_shows_people_link ADD CONSTRAINT FK_2F5AB85E5550C4ED FOREIGN KEY (pid) REFERENCES acts_people_data (id)");
        $this->addSql("CREATE INDEX IDX_2F5AB85E57167AB4 ON acts_shows_people_link (sid)");
        $this->addSql("CREATE INDEX IDX_2F5AB85E5550C4ED ON acts_shows_people_link (pid)");
        $this->addSql("ALTER TABLE acts_email_aliases CHANGE uid uid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_email_aliases ADD CONSTRAINT FK_CFB21822539B0606 FOREIGN KEY (uid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_CFB21822539B0606 ON acts_email_aliases (uid)");
        $this->addSql("ALTER TABLE acts_techies CHANGE showid showid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_techies ADD CONSTRAINT FK_4D00DAC2592D0E6F FOREIGN KEY (showid) REFERENCES acts_shows (id)");
        $this->addSql("CREATE INDEX IDX_4D00DAC2592D0E6F ON acts_techies (showid)");
        $this->addSql("ALTER TABLE acts_events CHANGE socid socid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_events ADD CONSTRAINT FK_78452C7AAF648A81 FOREIGN KEY (socid) REFERENCES acts_societies (id)");
        $this->addSql("CREATE INDEX IDX_78452C7AAF648A81 ON acts_events (socid)");
        $this->addSql("ALTER TABLE acts_knowledgebase CHANGE userid userid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_knowledgebase ADD CONSTRAINT FK_2582F999F132696E FOREIGN KEY (userid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_2582F999F132696E ON acts_knowledgebase (userid)");
        $this->addSql("ALTER TABLE acts_email CHANGE userid userid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_email ADD CONSTRAINT FK_91B3DECEF132696E FOREIGN KEY (userid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_91B3DECEF132696E ON acts_email (userid)");
        $this->addSql("ALTER TABLE acts_reviews CHANGE showid showid INT DEFAULT NULL, CHANGE uid uid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_reviews ADD CONSTRAINT FK_4F8219D8592D0E6F FOREIGN KEY (showid) REFERENCES acts_shows (id)");
        $this->addSql("ALTER TABLE acts_reviews ADD CONSTRAINT FK_4F8219D8539B0606 FOREIGN KEY (uid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_4F8219D8592D0E6F ON acts_reviews (showid)");
        $this->addSql("CREATE INDEX IDX_4F8219D8539B0606 ON acts_reviews (uid)");
        $this->addSql("ALTER TABLE acts_access CHANGE uid uid INT DEFAULT NULL, CHANGE issuerid issuerid INT DEFAULT NULL, CHANGE revokeid revokeid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_access ADD CONSTRAINT FK_2DAB5064539B0606 FOREIGN KEY (uid) REFERENCES acts_users (id)");
        $this->addSql("ALTER TABLE acts_access ADD CONSTRAINT FK_2DAB50646EEF703F FOREIGN KEY (issuerid) REFERENCES acts_users (id)");
        $this->addSql("ALTER TABLE acts_access ADD CONSTRAINT FK_2DAB5064C81B28E0 FOREIGN KEY (revokeid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_2DAB5064539B0606 ON acts_access (uid)");
        $this->addSql("CREATE INDEX IDX_2DAB50646EEF703F ON acts_access (issuerid)");
        $this->addSql("CREATE INDEX IDX_2DAB5064C81B28E0 ON acts_access (revokeid)");
        $this->addSql("ALTER TABLE acts_authtokens CHANGE userid userid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_authtokens ADD CONSTRAINT FK_11BF9FFBF132696E FOREIGN KEY (userid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_11BF9FFBF132696E ON acts_authtokens (userid)");
        $this->addSql("ALTER TABLE acts_performances CHANGE sid sid INT DEFAULT NULL, CHANGE venid venid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_performances ADD CONSTRAINT FK_E317F2D457167AB4 FOREIGN KEY (sid) REFERENCES acts_shows (id)");
        $this->addSql("ALTER TABLE acts_performances ADD CONSTRAINT FK_E317F2D4E176C6 FOREIGN KEY (venid) REFERENCES acts_societies (id)");
        $this->addSql("CREATE INDEX IDX_E317F2D457167AB4 ON acts_performances (sid)");
        $this->addSql("CREATE INDEX IDX_E317F2D4E176C6 ON acts_performances (venid)");
        $this->addSql("ALTER TABLE acts_email_sigs CHANGE uid uid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_email_sigs ADD CONSTRAINT FK_9EB1EE3E539B0606 FOREIGN KEY (uid) REFERENCES acts_users (id)");
        $this->addSql("CREATE INDEX IDX_9EB1EE3E539B0606 ON acts_email_sigs (uid)");
        $this->addSql("ALTER TABLE acts_config CHANGE name name VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE acts_access DROP FOREIGN KEY FK_2DAB5064539B0606");
        $this->addSql("ALTER TABLE acts_access DROP FOREIGN KEY FK_2DAB50646EEF703F");
        $this->addSql("ALTER TABLE acts_access DROP FOREIGN KEY FK_2DAB5064C81B28E0");
        $this->addSql("DROP INDEX IDX_2DAB5064539B0606 ON acts_access");
        $this->addSql("DROP INDEX IDX_2DAB50646EEF703F ON acts_access");
        $this->addSql("DROP INDEX IDX_2DAB5064C81B28E0 ON acts_access");
        $this->addSql("ALTER TABLE acts_access CHANGE uid uid INT NOT NULL, CHANGE issuerid issuerid INT NOT NULL, CHANGE revokeid revokeid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_applications DROP FOREIGN KEY FK_95ED3F0F592D0E6F");
        $this->addSql("ALTER TABLE acts_applications DROP FOREIGN KEY FK_95ED3F0FAF648A81");
        $this->addSql("DROP INDEX IDX_95ED3F0F592D0E6F ON acts_applications");
        $this->addSql("DROP INDEX IDX_95ED3F0FAF648A81 ON acts_applications");
        $this->addSql("ALTER TABLE acts_applications CHANGE showid showid INT NOT NULL, CHANGE socid socid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_auditions DROP FOREIGN KEY FK_BFECDAF7592D0E6F");
        $this->addSql("DROP INDEX IDX_BFECDAF7592D0E6F ON acts_auditions");
        $this->addSql("ALTER TABLE acts_auditions CHANGE showid showid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_authtokens DROP FOREIGN KEY FK_11BF9FFBF132696E");
        $this->addSql("DROP INDEX IDX_11BF9FFBF132696E ON acts_authtokens");
        $this->addSql("ALTER TABLE acts_authtokens CHANGE userid userid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_config CHANGE name name VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE acts_email DROP FOREIGN KEY FK_91B3DECEF132696E");
        $this->addSql("DROP INDEX IDX_91B3DECEF132696E ON acts_email");
        $this->addSql("ALTER TABLE acts_email CHANGE userid userid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_email_aliases DROP FOREIGN KEY FK_CFB21822539B0606");
        $this->addSql("DROP INDEX IDX_CFB21822539B0606 ON acts_email_aliases");
        $this->addSql("ALTER TABLE acts_email_aliases CHANGE uid uid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_email_sigs DROP FOREIGN KEY FK_9EB1EE3E539B0606");
        $this->addSql("DROP INDEX IDX_9EB1EE3E539B0606 ON acts_email_sigs");
        $this->addSql("ALTER TABLE acts_email_sigs CHANGE uid uid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_events DROP FOREIGN KEY FK_78452C7AAF648A81");
        $this->addSql("DROP INDEX IDX_78452C7AAF648A81 ON acts_events");
        $this->addSql("ALTER TABLE acts_events CHANGE socid socid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_knowledgebase DROP FOREIGN KEY FK_2582F999F132696E");
        $this->addSql("DROP INDEX IDX_2582F999F132696E ON acts_knowledgebase");
        $this->addSql("ALTER TABLE acts_knowledgebase CHANGE userid userid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_performances DROP FOREIGN KEY FK_E317F2D457167AB4");
        $this->addSql("ALTER TABLE acts_performances DROP FOREIGN KEY FK_E317F2D4E176C6");
        $this->addSql("DROP INDEX IDX_E317F2D457167AB4 ON acts_performances");
        $this->addSql("DROP INDEX IDX_E317F2D4E176C6 ON acts_performances");
        $this->addSql("ALTER TABLE acts_performances CHANGE sid sid INT NOT NULL, CHANGE venid venid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_reviews DROP FOREIGN KEY FK_4F8219D8592D0E6F");
        $this->addSql("ALTER TABLE acts_reviews DROP FOREIGN KEY FK_4F8219D8539B0606");
        $this->addSql("DROP INDEX IDX_4F8219D8592D0E6F ON acts_reviews");
        $this->addSql("DROP INDEX IDX_4F8219D8539B0606 ON acts_reviews");
        $this->addSql("ALTER TABLE acts_reviews CHANGE showid showid INT NOT NULL, CHANGE uid uid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_shows_people_link DROP FOREIGN KEY FK_2F5AB85E57167AB4");
        $this->addSql("ALTER TABLE acts_shows_people_link DROP FOREIGN KEY FK_2F5AB85E5550C4ED");
        $this->addSql("DROP INDEX IDX_2F5AB85E57167AB4 ON acts_shows_people_link");
        $this->addSql("DROP INDEX IDX_2F5AB85E5550C4ED ON acts_shows_people_link");
        $this->addSql("ALTER TABLE acts_shows_people_link CHANGE sid sid INT NOT NULL, CHANGE pid pid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_shows_refs DROP FOREIGN KEY FK_86C0B071592D0E6F");
        $this->addSql("DROP INDEX IDX_86C0B071592D0E6F ON acts_shows_refs");
        $this->addSql("ALTER TABLE acts_shows_refs CHANGE showid showid INT NOT NULL");
        $this->addSql("ALTER TABLE acts_techies DROP FOREIGN KEY FK_4D00DAC2592D0E6F");
        $this->addSql("DROP INDEX IDX_4D00DAC2592D0E6F ON acts_techies");
        $this->addSql("ALTER TABLE acts_techies CHANGE showid showid INT NOT NULL");
    }
}
