<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121218032004 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE acts_refresh_tokens (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, INDEX IDX_1A3F91E719EB6921 (client_id), INDEX IDX_1A3F91E7A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE acts_external_apps (id INT AUTO_INCREMENT NOT NULL, random_id VARCHAR(255) NOT NULL, redirect_uris LONGTEXT NOT NULL COMMENT '(DC2Type:array)', secret VARCHAR(255) NOT NULL, allowed_grant_types LONGTEXT NOT NULL COMMENT '(DC2Type:array)', name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, scope VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE acts_access_tokens (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, INDEX IDX_75B14F6819EB6921 (client_id), INDEX IDX_75B14F68A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE acts_auth_codes (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, redirect_uri LONGTEXT NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, INDEX IDX_D470A3A419EB6921 (client_id), INDEX IDX_D470A3A4A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE acts_refresh_tokens ADD CONSTRAINT FK_1A3F91E719EB6921 FOREIGN KEY (client_id) REFERENCES acts_external_apps (id)");
        $this->addSql("ALTER TABLE acts_refresh_tokens ADD CONSTRAINT FK_1A3F91E7A76ED395 FOREIGN KEY (user_id) REFERENCES acts_users (id)");
        $this->addSql("ALTER TABLE acts_access_tokens ADD CONSTRAINT FK_75B14F6819EB6921 FOREIGN KEY (client_id) REFERENCES acts_external_apps (id)");
        $this->addSql("ALTER TABLE acts_access_tokens ADD CONSTRAINT FK_75B14F68A76ED395 FOREIGN KEY (user_id) REFERENCES acts_users (id)");
        $this->addSql("ALTER TABLE acts_auth_codes ADD CONSTRAINT FK_D470A3A419EB6921 FOREIGN KEY (client_id) REFERENCES acts_external_apps (id)");
        $this->addSql("ALTER TABLE acts_auth_codes ADD CONSTRAINT FK_D470A3A4A76ED395 FOREIGN KEY (user_id) REFERENCES acts_users (id)");
        $this->addSql("ALTER TABLE acts_performances CHANGE sid sid INT DEFAULT NULL");
        $this->addSql("ALTER TABLE acts_news ADD public TINYINT(1) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE acts_refresh_tokens DROP FOREIGN KEY FK_1A3F91E719EB6921");
        $this->addSql("ALTER TABLE acts_access_tokens DROP FOREIGN KEY FK_75B14F6819EB6921");
        $this->addSql("ALTER TABLE acts_auth_codes DROP FOREIGN KEY FK_D470A3A419EB6921");
        $this->addSql("DROP TABLE acts_refresh_tokens");
        $this->addSql("DROP TABLE acts_external_apps");
        $this->addSql("DROP TABLE acts_access_tokens");
        $this->addSql("DROP TABLE acts_auth_codes");
        $this->addSql("ALTER TABLE acts_news DROP public");
        $this->addSql("ALTER TABLE acts_performances CHANGE sid sid INT NOT NULL");
    }
}
