<?php

namespace Acts\CamdramBundle\Entity;

use Doctring\ORM\Mapping as ORM;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function findNotExpiredOrderedByDateName(\DateTime $date)
    {
        $qb = $this->createQueryBuilder('a');
        $query = $qb->leftJoin('a.show', 's')
            ->where('a.expiresAt > :expires')
            ->andWhere('a.display = true')
            ->andWhere('s.authorised = true')
            ->orderBy('a.expiresAt, s.name')
            ->setParameter('expires', $date)
            ->getQuery();

        return $query->getResult();
    }

    private function getLatestQuery($limit, \DateTime $now)
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->leftJoin('a.show', 's')
            ->where('a.expiresAt > :expires')
            ->andWhere('a.display = true')
            ->andWhere('s.authorised = true')
            ->orderBy('a.updatedAt')
            ->setParameter('expires', $now)
            ->setMaxResults($limit);
    }

    public function findLatest($limit, \DateTime $now)
    {
        return $this->getLatestQuery($limit, $now)->getQuery()->getResult();
    }

    public function findLatestBySociety(Society $society, $limit, \DateTime $now)
    {
        return $this->getLatestQuery($limit, $now)
            ->andWhere(':society MEMBER OF s.societies')->setParameter('society', $society)
            ->getQuery()->getResult();
    }

    public function findLatestByVenue(Venue $venue, $limit, \DateTime $now)
    {
        return $this->getLatestQuery($limit, $now)
            ->andWhere('EXISTS (SELECT p FROM \Acts\CamdramBundle\Entity\Performance p WHERE p.show = s AND p.venue = :venue)')
            ->setParameter('venue', $venue)
            ->getQuery()->getResult();
    }

    public function findOneById($id, \DateTime $now)
    {
        $qb = $this->createQueryBuilder('a');

        return $qb->leftJoin('a.show', 's')
            ->where('a.expiresAt > :expires')
            ->andWhere('a.id = :id')
            ->andWhere('s.authorised = true')
            ->setParameter('id', $id)
            ->setParameter('expires', $now)
            ->getQuery()->getOneOrNullResult();
    }

    public function findOneByShowAndId($slug, $advertId)
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.show', 's')
            ->where('s.slug = :slug')
            ->andWhere('a.id = :id')
            ->setParameter('slug', $slug)
            ->setParameter('id', $advertId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
