<?php

namespace Acts\CamdramBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Query\Expr;

/**
 * AuditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditionRepository extends EntityRepository
{
    /**
     * CurrentOrderedByNameDate
     *
     * Find all auditions between two dates that should be shown on the
     * diary page, joined to the corresponding show.
     *
     * @param integer $startDate start date expressed as a Unix timestamp
     * @param integer $endDate emd date expressed as a Unix timestamp
     *
     * @return array of auditions
     */
    public function findCurrentOrderedByNameDate()
    {
        $query_res = $this->getEntityManager()->getRepository('ActsCamdramBundle:Audition');
        $query = $query_res->createQueryBuilder('a')
            ->leftJoin('ActsCamdramBundle:Show', 's', Expr\Join::WITH, 'a.show = s.id')
            ->where('a.date >= CURRENT_DATE()')
            ->andWhere('a.display = 0')
            ->andWhere('a.non_scheduled = 0')
            //->andWhere('s.authorize_id > 0')
            ->orderBy('s.name, a.date, a.start_time')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * findScheduledJoinedToShow
     *
     * Find all auditions between two dates that should be shown on the
     * diary page, joined to the corresponding show.
     *
     * @param integer $startDate start date expressed as a Unix timestamp
     * @param integer $endDate emd date expressed as a Unix timestamp
     *
     * @return array of auditions
     */
    public function findScheduledJoinedToShow($startDate, $endDate)
    {
        $query_res = $this->getEntityManager()->getRepository('ActsCamdramBundle:Audition');
        $query = $query_res->createQueryBuilder('a')
            ->leftJoin('ActsCamdramBundle:Show', 's', Expr\Join::WITH, 'a.show = s.id')
            ->where('a.date <= :enddate')
            ->andWhere('a.date >= :startdate')
            ->andWhere('a.non_scheduled = 0')
            ->andWhere('a.date >= CURRENT_DATE()')
            ->setParameters(array(
                'startdate' => date("Y/m/d", $startDate),
                'enddate' => date("Y/m/d", $endDate)
                ))
            ->orderBy('a.date')
            ->getQuery();

        return $query->getResult();
    }

    public function findUpcoming($limit)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('ActsCamdramBundle:Show', 's', Expr\Join::WITH, 'a.show = s.id')
            ->where('a.date >= CURRENT_DATE()')
            ->andWhere('a.non_scheduled = 0')
            ->andWhere('a.show IS NOT NULL')
            ->orderBy('a.date')
            ->addOrderBy('a.start_time')
            ->setMaxResults($limit)
            ->getQuery();
        return $query->getResult();
    }
}
