<?php

namespace Acts\CamdramBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailBuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailBuilderRepository extends EntityRepository
{    
    public function selectAll()
    {    
        $qb = $this->createQueryBuilder('s')
            ->orderBy('s.id', 'desc');
        return $qb;
    }
    
    public function queryByIds($ids)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.id in (:ids)')
            ->setParameter('ids', $ids)
            ->orderBy('s.id', 'desc');
        return $qb;    
    }    
}
