<?php

namespace Acts\CamdramBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocietyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocietyRepository extends EntityRepository
{
    /**
     * findAllOrderedByCollegeName
     *
     * Finds all societies and order them by college, followed by name.
     */
    public function findAllOrderedByCollegeName()
    {
        /* Do we care about affiliation to ACTS anymore? */
        return $this->getEntityManager()
            ->createQuery('SELECT s FROM ActsCamdramBundle:Society s ORDER BY s.college, s.name')
            ->getResult();
    }

}
