maintainer       "Peter Hoyes"
maintainer_email "pahoyes@gmail.com"
license          "MIT"
description      "Installs/Configures camdram"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1"
depends "apache2"
depends "apt", "= 1.7"
depends "build-essential"
depends "composer"
depends "database"
depends "mysql"
depends "openssl"
depends "php"
depends "symfony2"
