<?php
namespace Acts\CamdramSecurityBundle\EventListener;

use Psr\Log\LoggerInterface;
use Doctrine\ORM\Event\LifecycleEventArgs;

use Acts\CamdramSecurityBundle\Entity\AccessControlEntry;

/**
 * AccessControlEntryListener
 *
 * Functions triggered by events generated by the Security Bundle. These functions
 * result in information being logged by Camdram.
 *
 */
class AccessControlEntryListener
{
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    /**
     * Log the person has been granted access to a resource on the site.
     */
    public function postPersist(AccessControlEntry $ace, LifecycleEventArgs $event)
    {
        /* TODO some logging */
    }
}
