<?php
namespace Acts\CamdramSecurityBundle\EventListener;

use Doctrine\ORM\Event\LifecycleEventArgs;

use Acts\CamdramSecurityBundle\Entity\PendingAccess,
    Acts\CamdramSecurityBundle\Service\EmailDispatcher;

/**
 * PendingAccessListener
 *
 * Functions triggered by events generated by the Security Bundle. These functions
 * result in automated emails being sent by Camdram.
 *
 */
class PendingAccessListener
{
    private $email_dispatcher;

    public function __construct(EmailDispatcher $dispatcher)
    {
        $this->email_dispatcher = $dispatcher;
    }

    /**
     * Inform the person that they have been granted access to a resource on the
     * site, pending creating an account.
     */
    public function postPersist(PendingAccess $pending_ace, LifecycleEventArgs $event)
    {

        $this->email_dispatcher->sendPendingAceEmail($pending_ace);
    }
}

