acts_camdram_security_change_email:
    path: /change-email
    defaults: { _controller: ActsCamdramSecurityBundle:Account:changeEmail }
acts_camdram_security_resend_verification:
    path: /resend-verification
    defaults: { _controller: ActsCamdramSecurityBundle:Account:resendVerification }
acts_camdram_security_unlink_account:
    path: /unlink-account/{service}
    defaults: { _controller: ActsCamdramSecurityBundle:Account:unlinkAccount }
