# This is a basic workflow to help you get started with Actions

name: Site availablilty checks

# Controls when the workflow will run
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check www.camdram.net and camdram.net, at both http and https
        run: |
            get () {
                wget --max-redirect=0 -O output.html $2 2>stderr || true ${rval:=$?}
                cat stderr
                if [ $rval -ne $1 ]; then
                    exit 1
                fi
            }
            get 0 https://www.camdram.net
            grep -F '200 OK' stderr
            grep -F 'Welcome to Camdram' output.html
            get 8 http://camdram.net
            grep -F 'Location: https://www.camdram.net/ [following]' stderr
            get 8 http://www.camdram.net
            grep -F 'Location: https://www.camdram.net/ [following]' stderr
            get 8 https://camdram.net
            grep -F 'Location: https://www.camdram.net/ [following]' stderr
