name: Deploy releases

on:
  release:
    types: [published]

  workflow_dispatch:

concurrency: deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract tag name
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}

    - name: Deploy
      uses: deployphp/action@v1
      with:
        private-key: ${{ secrets.ANTIGONE_PRIVATE_KEY }}
        dep: deploy production --tag ${{ steps.get_tag.outputs.TAG }}
